packages:
  - apps/*
  - libs/*
  - libs/shared/*
  - libs/mf/*
  - libs/server/*
  - libs/server/shared
  - libs/server/catalog-svc
autoInstallPeers: true
overrides:
  '@angular/router': 20.3.29
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
  - unrs-resolver
neverBuiltDependencies:
  - '@apollo/protobufjs'
  - '@scarf/scarf'
  - less
  - workerd
allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@parcel/watcher': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  nx: set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
